# Generated by Django 5.1.5 on 2025-01-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_inventory_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerPhone', models.BigIntegerField(primary_key=True, serialize=False)),
                ('purchase_count', models.IntegerField(default=0)),
                ('total_purchase_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('salesId', models.AutoField(primary_key=True, serialize=False)),
                ('customerPhone', models.BigIntegerField()),
                ('barcode', models.CharField(max_length=255)),
                ('productName', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('netTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
