# Generated by Django 5.1 on 2025-02-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customer_salesrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='customerPhone',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='price',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='productName',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='total',
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='netTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=255)),
                ('productName', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.salesrecord')),
            ],
        ),
    ]
