# Generated by Django 5.1 on 2025-02-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_salesrecord_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
