# Generated by Django 5.1 on 2025-02-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_salesrecord_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
