# Generated by Django 5.1 on 2025-02-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_salesrecord_discount_alter_salesrecord_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='discountAmmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='vatAmmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
