# Generated by Django 5.1 on 2025-02-18 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_salesrecord_discountammount_salesrecord_vatammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
