# Generated by Django 5.1.6 on 2025-02-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_inventory_created_inventory_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
