# Generated by Django 5.1.6 on 2025-02-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_inventory_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='paymentMethod',
            field=models.CharField(default='Cash', max_length=10),
        ),
    ]
