# Generated by Django 5.1.6 on 2025-03-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_salesrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='createdBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
