# Generated by Django 5.1.6 on 2025-03-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_inventory_createdby_inventory_updatedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcodes', models.CharField(max_length=255, unique=True)),
                ('product', models.CharField(max_length=255, null=True)),
                ('is_assigned', models.BooleanField()),
            ],
        ),
    ]
