# Generated by Django 5.1.6 on 2025-03-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_barcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodes',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
