# Generated by Django 5.1.6 on 2025-03-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_barcodes_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodes',
            name='barcode_svg',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
