# Generated by Django 5.1.6 on 2025-03-27 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_barcodes_barcode_svg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('R', 'Regular'), ('S', 'Silver'), ('G', 'Gold'), ('D', 'Diamond')], default='R', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customerName',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='memberShip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.membership'),
        ),
    ]
