# Generated by Django 5.1.6 on 2025-03-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_customer_membership_customer_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='plan',
        ),
        migrations.AddField(
            model_name='customer',
            name='memberShipPlan',
            field=models.CharField(choices=[('R', 'Regular'), ('S', 'Silver'), ('G', 'Gold'), ('D', 'Diamond')], default='R', max_length=20),
        ),
    ]
