# Generated by Django 5.1.6 on 2025-03-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_customer_plan_customer_membershipplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='memberShipPlan',
            new_name='membershipPlan',
        ),
    ]
